spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: vote-sicredi

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password123

cpf:
  api:
    url: https://user-info.herokuapp.com/

api:
  version: v1
